import type { RawData } from '../types';
import raw from './checklist-data.json';

// 604 checks across 61 sections, extracted from the InTouch ACP rev 18 export.
// Generated by tools/extract.py in the original demo — never hand-edit; see
// app/ARCHITECTURE_3.md "Data extraction" for how to regenerate it.
export const RAW: RawData = raw as unknown as RawData;
